project:
  type: website
  render:
    - "*.qmd"
    - "!Course_contributions/"
    - "!intro_to_programming"
    - "!Toolbox"
    - "!R/ANOVA-lm"
    - "!R/timeseries"
    - "!R/UQ R User Group"

website:
  title: "UQ Library Technology Training"
  navbar:
    search: true
    left:
      - href: index.qmd
        text: "Home"
      - href: Orientation/orientation.qmd
        text: "O-Week"
    tools:
      - icon: github
        href: https://github.com/uqlibrary/technology-training
  
  sidebar:
    style: "docked"
    collapse-level: 1
    contents:
      - text: "Acrobat"
        href: Acrobat/acrobat.qmd
      - text: "Audacity"
        href: Audacity/audacity.qmd
      - text: "Excel"
        href: Excel/excel.qmd
      - text: "GenAI"
        href: GenAI/genai.qmd
      - section: "Git"
        contents:
          - text: "Git from the command line"
            href: Git/git.qmd
          - text: "GitHub and portfolios"
            href: Git/GitHub/GitHub_intro.qmd
      - text: "LaTeX with Overleaf"
        href: LaTeX/overleaf_latex.qmd
      - text: "NVivo"
        href: NVivo/nvivo.qmd
      - text: "OpenRefine"
        href: OpenRefine/openrefine.qmd
      - text: "OpenStreetMap"
        href: OSM/OpenStreetMap.qmd
      - text: "Photoshop"
        href: Photoshop/photoshop.qmd
      - text: "PowerPoint"
        href: PowerPoint/powerpoint.qmd
      - text: "Premiere Pro"
        href: Premiere_Pro/premiere_pro.qmd
      - section: "Python"
        contents:
          - text: "1. Fundamentals"
            href: Python/1-fundamentals/fundamentals.qmd
          - text: "2. Data processing"
            href: Python/2-data_processing/data_processing.qmd
        # - text: "3. Visualisation"
        #   href: Python/3-intro_visualisation
        # - text: "4. Statistics and more visualisations"
        #   href: Python/4-stats_and_further_vis
      - section: "QGIS"
        contents:
          - text: "1. Introduction"
            href: QGIS/intro/QGIS_intro.qmd
          - text: "2. Raster analysis"
            href: QGIS/raster/QGIS_raster.qmd
          - text: "3. Vector analysis"
            href: QGIS/vector/QGIS_vector.qmd
          - text: "4. Mobile mapping"
            href: QGIS/mobile/QGIS_mobile.qmd
      - section: "Qualtrics"
        href: Qualtrics/qualtrics.qmd
      - section: "R with RStudio"
        href: R/installation.qmd
        contents:
          - text: "1. Getting started"
            href: R/rstudio_intro/rstudio_intro.qmd
          - text: "2. dplyr: data transformation"
            href: R/dplyr/dplyr.qmd
          - text: "3. ggplot2: introduction to visualisation"
            href: R/ggplot2_intro/ggplot2_intro.qmd
          - text: "4. ggplot2: intermediate visualisation"
            href: R/ggplot2_intermediate/ggplot2_intermediate.qmd
          - text: "5. tidyr and purrr: tidying and loops"
            href: R/tidyverse_next_steps/tidyverse_next_steps.qmd
          - text: "6. Quarto: reproducible publishing"
            href: R/reports/reports.qmd
          - text: "7. Heatmaps"
            href: R/heatmaps/heatmaps_intermediate.qmd
          - text: "8. Shiny web apps"
            href: R/shiny/shiny.qmd
          - text: "9. Functions and packaging"
            href: R/packaging/packaging.qmd
      - text: "uMap"
        href: uMap/umap_intro.qmd
      - text: "Unix Shell"
        href: Shell/shell_intro.qmd
      - text: "Voyant Tools"
        href: Voyant/voyant.qmd
      - text: "Word"
        href: Word/word.qmd

format:
  html:
    theme: 
      - pulse
      - styles.scss
    toc: true
    df-print: paged

execute:
  # only re-render if there is a code change
  freeze: auto