---
title: "Training elsewhere"
---

Apart from the [training the UQ Library offers](https://web.library.uq.edu.au/study-and-learning-support/training-and-workshops), here are other providers, at UQ and elsewhere.

## At UQ

### CBCS

The Centre for Biodiversity and Conservation Science hosts [seminars and workshops](https://cbcs.centre.uq.edu.au/events), notably the [R Workshops @ UQ](https://cbcs.centre.uq.edu.au/events-and-seminars/r-workshops-uq) series.

### Data Science CRP

The [Data Science Collaborative Research Platform](https://research-support.uq.edu.au/resources-and-support/facilities-and-infrastructure/data-science-collaborative-research-platform) (Data Science CRP) provides support and training on topics like bioinformatics, statistics, biometry and applied AI.

### Graduate School CDF

The [Graduate School Career Development Framework](https://cdf.graduate-school.uq.edu.au/events/research-skills) (Graduate School CDF) lists various workshop directed at HDR students, including training offered by the Data Science CRP and the Institute for Social Science Research (ISSR).

### LADAL

The [Language Technology and Data Analysis Laboratory](https://ladal.edu.au/) (LADAL) offers numerous open educational resources, in particular on the topic of text analysis with R.

### Research Computing Centre

The [Research Computing Centre](https://rcc.uq.edu.au/training-support/training-courses) (RCC) offers training on High Performance Computing, as well as research platforms like Galaxy.

## Around UQ

### The Carpentries

[The Carpentries](https://carpentries.org/) is a global, non-profit organisation offering workshops to learn foundation coding and data science skills to researchers. See [upcoming workshops](https://carpentries.org/workshops/upcoming-workshops/).