---
title: "Further resources for Python users"
editor: source
date: today
author: UQ Library
---

## Books and tutorials

### Data science

* [_Python data science handbook_](https://jakevdp.github.io/PythonDataScienceHandbook/) by Jake VanderPlas
* [_Scipy Lecture Notes_](https://lectures.scientific-python.org/) to learn numerical computing, data science and plotting with Python
* [_10 Minutes to pandas_](https://pandas.pydata.org/pandas-docs/stable/user_guide/10min.html), an introduction to pandas' capabilities
* [_Programming with Python_](https://swcarpentry.github.io/python-novice-inflammation/) and [Plotting and Programming in Python](https://swcarpentry.github.io/python-novice-gapminder/), two lessons by The Carpentries

### General programming

* [Official Python 3 Tutorial](https://docs.python.org/3/tutorial/index.html) (for users already familiar with programming concepts)
* [_Python for Everybody_](https://www.py4e.com/lessons) (PY4E), by Charles R. Severance (no programming background needed)
* [Python courses on LinkedIn Learning](https://www.linkedin.com/learning/topics/python) ([use your UQ credentials](https://web.library.uq.edu.au/study-and-learning-support/training-and-workshops/linkedin-learning-online-courses) to access the full catalogue)
* [_Python Programming_](https://en.wikibooks.org/wiki/Python_Programming) on WikiBooks
* [_The Hitchhiker's Guide to Python_](https://docs.python-guide.org/)

## Documentation

* [Official Python 3 documentation](https://docs.python.org/3/)

## Questions and answers

* [Python Questions and Answers on StackOverflow](https://stackoverflow.com/questions/tagged/python)

## Practice Python

* [Exercism's Python track](https://exercism.org/tracks/python)
* [_Python Challenge_](http://www.pythonchallenge.com/index.php), an interactive riddle
* [_Practice Python_](https://www.practicepython.org/) with beginner exercises
* [CodingBat's Python problems](https://codingbat.com/python)

## At UQ

* See the [next sessions](https://web.library.uq.edu.au/study-and-learning-support/training-and-workshops/online-and-person-workshops) at the Library
* Join the monthly [UQ Python User Group](https://uqpug.github.io/) (UQPUG) to collaborate and share with other Python users
* Ask questions to other researchers during the weekly [Hacky Hour](https://rcc.uq.edu.au/training-support/meetups)
* Contact your unit's statistician

## Training outside the Library

* Find more training providers, at and outside UQ, in our ["Training Elsewhere" page](../more_training.qmd)
