---
title: "Installation instructions for R workshops"
editor: source
date: last-modified
author: UQ Library
---

{{< embed installation_banner.qmd >}}

Participants are welcome to bring and use their own laptops with the software already installed (with a working Internet connection), to ensure that you can continue using what you learn once you leave the workshop. However, feel free to use one of the Library's desktop computers (for in-person workshops), a [Library loan laptop](https://web.library.uq.edu.au/library-and-student-it-help/using-library-devices/laptop-loans), or a UQ-provided device, as they all offer the necessary software.

R code can be written in various applications. Two of the most popular ones are [RStudio](https://posit.co/downloads) and [Positron](https://positron.posit.co/).

Before the start of the workshop, please go through the installation steps below to install both R and either RStudio or Positron (check the workshop description to know which one). Please also make sure that the software runs as expected once it is installed.

## UQ computers

If you have an ITS-managed computer, you can install R and RStudio/Positron from Company Portal (Windows) or Self Service (macOS).

If you use a Library-managed computer, you can install RStudio/Positron in ZENworks (which automatically installs R too).

## Your own device

### Windows

* [Download R from the official website](https://cran.r-project.org/bin/windows/base/release.htm).
* Run the .exe file that was just downloaded.
* Go to the [RStudio download page](https://posit.co/download/rstudio-desktop/#download) or the [Positron download page](https://positron.posit.co/download.html) and follow the instructions to download and install it.
* Once it's installed, open RStudio/Positron to make sure it works and there is no error message.

### macOS

* [Go to the R website](https://cran.r-project.org/bin/macosx/).
* Select the .pkg file for the version of macOS that you have.
* Double-click on the file that was downloaded and R will install.
* Go to the [RStudio download page](https://posit.co/download/rstudio-desktop/#download) or the [Positron download page](https://positron.posit.co/download.html) and follow the instructions to download and install it.
* Once it's installed, open RStudio/Positron to make sure it works and there is no error message.

### Linux

* Download R by following the instructions for your distribution from [CRAN](https://cran.r-project.org/). For most distributions, you can use your package manager (e.g. for Debian/Ubuntu run `sudo apt-get install r-base`, and for Fedora run `sudo yum install R`).
* Go to the [RStudio download page](https://posit.co/download/rstudio-desktop/#download) or the [Positron download page](https://positron.posit.co/download.html) and follow the instructions to download and install it.
* Once it's installed, open RStudio/Positron to make sure it works and there is no error message.
