---
title: "Further resources for R users"
editor: source
date: last-modified
author: UQ Library
---

## Cheatsheets

* [Cheatsheets about R packages, Positron and RStudio](https://posit.co/resources/cheatsheets/).

## Tutorials, manuals and books

* _[R for Data Science](https://r4ds.hadley.nz/)_, excellent free online book by Hadley Wickham, Mine Çetinkaya-Rundel, and Garrett Grolemund
* Two introductory materials to R by The Carpentries: [R for Reproducible Scientific Analysis](https://swcarpentry.github.io/r-novice-gapminder/) and [Data Analysis and Visualization in R for Ecologists](https://datacarpentry.github.io/R-ecology-lesson/)
* Why use R over Excel for your analyses? This post provides arguments and a short introduction to R: _[Excel vs R: A Brief Introduction to R](https://www.jessesadler.com/post/excel-vs-r/)
* _[RStudio Education](https://education.rstudio.com/)_ lists useful resources
* CRAN's [basic and advanced manuals](https://cran.r-project.org/manuals.html)
* Lots of quality tutorials on [STHDA](http://www.sthda.com/english/)
* DataCamp's R [documentation](https://www.datacamp.com/doc/r/category/r-documentation)
* Lots of quality tutorials on _[Cookbook for R](http://www.cookbook-r.com/)_
* [LinkedIn Learning R courses](https://www.linkedin.com/learning/topics/r) (use your UQ credentials)
* Many excellent books on [Bookdown.org](https://bookdown.org/)
* Various [tutorials by LADAL](https://ladal.edu.au/tutorials.html), many focused on language analysis

## Practice

* Solve challenges and learn from other people's solutions on [Exercism](https://exercism.org/tracks/r)
* [{swirl}](https://swirlstats.com/) is a package that allows you to learn R interactively in an R session
* The [{learnr}](https://rstudio.github.io/learnr/) package integrates into RStudio's "Tutorial" tab

## Data visualisation

* Official ggplot2 resources:
  * [ggplot2 cheatsheet](https://www.rstudio.org/links/data_visualization_cheat_sheet)
  * [ggplot2 website](https://ggplot2.tidyverse.org/), including 
  * [ggplot2 documentation](https://ggplot2.tidyverse.org/reference/)
* Online books:
  * _R for Data Science_ has a [chapter on data visualisation](https://r4ds.hadley.nz/data-visualize.html) which introduces ggplot2 early as it is used in various other chapters
  * The book _[ggplot2: Elegant Graphics for Data Analysis_](https://ggplot2-book.org/)_ explains the Grammar of Graphics and details how ggplot2 works
  * Nicola Rennie's book _[The Art of Data Visualization with ggplot2](https://nrennie.rbind.io/art-of-viz/)_ guides your through the whole process of creating various refined data visualisation
  * Winston Chang's _[R Graphics Cookbook](https://r-graphics.org/)_ goes through most aspects of ggplot2 using bite-size examples
  * Carson Sievert's _[Interactive web-based data visualization with R, plotly, and shiny](https://plotly-r.com/)_ to learn more about plotly and exploratory data analysis
* Further resources:
  * [A comparison of Base R and and ggplot2](https://jtr13.github.io/cc21fall2/base-r-vs.-ggplot2-visualization.html) by Yiquan Li and Zezhong Fan
  * [From Data to Viz](https://www.data-to-viz.com/) and the companion [R Graph Gallery](https://www.r-graph-gallery.com/) to explore different visualisations and the code that generates them
  * Cédric Scherer's [Effective Data Visualisation](https://z3tt.github.io/bespokeDS/) presentation is packed with useful tips
  * [Coding Club's data visualisation tutorial](https://ourcodingclub.github.io/tutorials/datavis/)

## Questions and answers

* [Questions about R programming](http://stackoverflow.com/questions/tagged/r) on StackOverflow
* [Statistics questions using R](https://stats.stackexchange.com/questions/tagged/r) on CrossValidated

## Documentation

* Packages from CRAN and Bioconductor on [Rdocumentation](http://www.rdocumentation.org/)
* Packages from CRAN, Bioconductor, R-Forge and GitHub (and run R code online) on [rdrr.io](https://rdrr.io/)

## R news

* Daily news and tutorials on [R-bloggers](https://www.r-bloggers.com/)
* Weekly digest of R news on [R Weekly](https://rweekly.org/)
* [Tidyverse (and Tidymodels) news](https://tidyverse.org/blog/)

## At UQ

* See the [next sessions](https://web.library.uq.edu.au/study-and-learning-support/training-and-workshops/online-and-person-workshops) at the Library
* Join the monthly [UQ R User Group](https://uqrug.netlify.app/) (UQRUG) to collaborate and share with other R users
* Ask questions to other researchers during the weekly [Hacky Hour](https://rcc.uq.edu.au/training-support/meetups)
* Contact your unit's statistician

## Training outside the Library

* Find more training providers, at and outside UQ, in our ["Training Elsewhere" page](../more_training.qmd)
